version: 2

buildSteps: &buildSteps
  - setup_remote_docker
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: test
      command: npm test
  - persist_to_workspace:
      # Persist all job output, so we can (potentially) use it for deploys
      root: ../
      paths:
        - ./node-*

jobs:
  'node-8':
    docker:
      - image: circleci/node:8
    working_directory: ~/node-8
    steps: *buildSteps

  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/node-10
    steps: *buildSteps

  'node-12':
    docker:
      - image: circleci/node:12
    working_directory: ~/node-12
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - 'node-8'
      - 'node-10'
      - 'node-12'
